---
- name: Update Homebrew sudoers to preserve required env vars
  ansible.builtin.copy:
    dest: /etc/sudoers.d/homebrew
    content: |
      {{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL
    mode: "0440"
  become: true
  tags:
    - sudo
